export enum ASYNC_STORAGE_KEY {
  TOKEN = 'TOKEN',
  ID = 'ID',
  PWD = 'PWD',
  DEEP_LINK = 'DEEP_LINK',
  IS_REQUEST_PERMISSION_PUSH_NOTI = 'IS_REQUEST_PERMISSION_PUSH_NOTI',
}

export enum FONT {
  LARGE_TITLE = 'LARGE_TITLE', //35
  TITLE_1 = 'TITLE_1', //28
  TITLE_2 = 'TITLE_2', // 23
  TITLE_3 = 'TITLE_3', // 21
  BODY = 'BODY', // 18
  SUB_HEAD = 'SUB_HEAD', // 15
  SUB_HEAD_2 = 'SUB_HEAD_2', // 17
  LOGO_TITLE = 'LOGO_TITLE', // 39
  CAPTION = 'CAPTION', // 13
  CAPTION_2 = 'CAPTION_2', // 12
  CAPTION_3 = 'CAPTION_3', // 10
  CAPTION_4 = 'CAPTION_4', // 11
  CAPTION_5 = 'CAPTION_5', // 9
  CAPTION_6 = 'CAPTION_6', // 14
  CAPTION_7 = 'CAPTION_7', // 16
  CAPTION_8 = 'CAPTION_8', // 20
  CAPTION_9 = 'CAPTION_9', // 22
  CAPTION_10 = 'CAPTION_10', // 24
  CAPTION_11 = 'CAPTION_11', // 26
}

export enum FONT_FAMILY {
  LIGHT = 'Pretendard-Light', // 300
  REGULAR = 'Pretendard-Regular', // 400
  MEDIUM = 'Pretendard-Medium', // 500
  SEMI_BOLD = 'Pretendard-SemiBold', //600
  BOLD = 'Pretendard-Bold', //700
}

export enum IS_ACTIVE {
  NO = 'N',
  YES = 'Y',
  A = 'A',
}

export enum GENDER {
  MALE = 'M',
  FEMALE = 'F',
}

export enum EMIT_EVENT {
  'UPDATED_USER' = 'UPDATED_USER',
  'LOGOUT' = 'LOGOUT',
  'CURRENT_LOCATION' = 'CURRENT_LOCATION',
  'RECOMMEND_PARKING' = 'RECOMMEND_PARKING',
  'ADD_REVIEW' = 'ADD_REVIEW',
  'MONTHLY_PARKING_DIRECT' = 'MONTHLY_PARKING_DIRECT',
  'RELOAD_QNA_BBS' = 'RELOAD_QNA_BBS',
  'VALET_PARKING' = 'VALET_PARKING',
  'CHANGE_QNA_BBS_REPLY_LIST' = 'CHANGE_QNA_BBS_REPLY_LIST',
  'VALET_MAIN_NOTICE' = 'VALET_MAIN_NOTICE',
  'PING_ON_MAP' = 'PING_ON_MAP',
  'BBS_NOTICE' = 'BBS_NOTICE',
  'SEARCH_BAR' = 'SEARCH_BAR',
  'DATA_EVAL' = 'DATA_EVAL',
  'EXIT_APP' = 'EXIT_APP',
  'PAYMENT_CARD' = 'PAYMENT_CARD',
  'UPDATED_CAR' = 'UPDATED_CAR',
  'REFETCH_QUICK_RESERVATION' = 'REFETCH_QUICK_RESERVATION',
  'DATA_SEARCH_KAKAO' = 'DATA_SEARCH_KAKAO',
  'ROAD_OPPOSITE' = 'ROAD_OPPOSITE',
  'RELOAD_ROUTE_PASSENGER' = 'RELOAD_ROUTE_PASSENGER',
  'RELOAD_ROUTE_DRIVER' = 'RELOAD_ROUTE_DRIVER',
  'FOCUS_INPUT_WAY_2' = 'FOCUS_INPUT_WAY_2',
  'FOCUS_INPUT_DRIVER_WAY_2' = 'FOCUS_INPUT_DRIVER_WAY_2',
  'REFETCH_DATA_CARPOOL' = 'REFETCH_DATA_CARPOOL',
  'CARPOOL_PAYMENT_COMPLETE' = 'CARPOOL_PAYMENT_COMPLETE',
  'CARPOOL_RUNNING' = 'CARPOOL_RUNNING',
  'CARPOOL_COMPLETED' = 'CARPOOL_COMPLETED',
  'REFETCH_ROUTE_REQUEST_INFO' = 'REFETCH_ROUTE_REQUEST_INFO',
  'CARPOOL_WAY_TO_WORK' = 'CARPOOL_WAY_TO_WORK',
  'CARPOOL_PAYMENT_CARD' = 'CARPOOL_PAYMENT_CARD',
  'NOTIFICATION_ID_CHAT_DETAIL' = 'NOTIFICATION_ID_CHAT_DETAIL',
  'PASSENGER_CANCEL_PAYMENT' = 'PASSENGER_CANCEL_PAYMENT',
  'DRIVER_CANCEL_PAYMENT' = 'DRIVER_CANCEL_PAYMENT',
}

export enum PARKING_FILTER_TYPE {
  ALLOWBOOKING = 'ALLOWBOOKING',
  ALLOWBOOKINGPARTNER = 'ALLOWBOOKINGPARTNER',
  IFFREE = 'IFFREE',
  PRIVATE = 'PRIVATE',
  PUBLIC = 'PUBLIC',
  GREENCAR = 'GREENCAR',
  CARD = 'CARD',
  ELEC = 'ELEC',
  SHARECAR = 'SHARECAR',
  FREE = 'FREE',
  WEEKDAY = 'WEEKDAY',
  WEEKEND = 'WEEKEND',
  NIGHT = 'NIGHT',
  MONTH = 'MONTH',
  WEEKDAYTIME = 'WEEKDAYTIME',
  WEEKENDTIME = 'WEEKENDTIME',
  DINNER = 'DINNER',
  CONNIGHT = 'CONNIGHT',
}

export enum LIST_OF_PARKING_FILTER_TYPE {
  CHARGE_INCREASE = 'CHARGE_INCREASE',
  DISTANCE_INCREASE = 'DISTANCE_INCREASE',
}

export enum TERMINAL_SELECT {
  'VALET_ONE' = 'valetOne',
  'VALET_TWO' = 'valetTwo',
}

export enum PAYMENT_METHOD {
  'CREDIT_CARD' = 'CREDIT_CARD',
  'CELL_PHONE' = 'CELL_PHONE',
}

export enum DATE_PICKER_MODE {
  'DATE' = 'date',
  'DATETIME' = 'datetime',
  'TIME' = 'time',
}

export enum TYPE_IMAGE {
  'jpeg' = 'image/jpeg',
  'png' = 'image/png',
}

export enum BOOKING_STATUS {
  BOOKING_SUCCESS = 'BOOKING_SUCCESS',
  FINISHED = 'FINISHED',
}

export enum AUTO_MESSAGE_TYPE {
  'ROUTE_OPERATION_REQUEST' = '3',
  'CARPOOL_REQUEST' = '4',
  'PASSENGER_CANCEL_RESERVATION' = '5',
  'DRIVER_CANCEL_RESERVATION' = '6',
  'ROUTE_OPERATION_REGISTRATION' = '7',
  'CARPOOL_APPROVAL' = '8',
  'COMPLETE_PAYMENT' = '9',
  'CARPOOL_COMPLETED' = '10',
  'RESQUEST_RESPONSE' = '11',
  'DRIVER_CARPOOL_REQUEST' = '12',
  'PASSENGER_LEFT' = '13',
  'DRIVER_LEFT' = '14',
  'DRIVER_REPLY' = '15',
  'CARPOOL_RUNNING' = '16',
  'PASSENGER_CANCEL_PAYMENT' = '17',
  'DRIVER_CANCEL_PAYMENT' = '18',
  'DRIVER_CHANGE_AMOUNT' = '19',
  'PASSENGER_CARPOOL_REQUEST' = '20',
}

export enum DRIVER_STATUS_REGISTRATION {
  NOT_COMPLETE = 'NOT_COMPLETE',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum PAYMENT_HISTORY_METHOD {
  IN_APP = 'IN_APP',
  CARD = 'CARD',
}

export enum TYPE_BLOCK {
  PASSENGER = 'PASSENGER',
  DRIVER = 'DRIVER',
}

export enum REPORT_TYPE {
  NOT_APPEAR_AT_CARPOOL = 'NOT_APPEAR_AT_CARPOOL',
  CARPOOL_VEHICLE_IS_DIFFERENT = 'CARPOOL_VEHICLE_IS_DIFFERENT',
  UNPLEASANT_CONVERSATION = 'UNPLEASANT_CONVERSATION',
  ADDITIONAL_PAYMENT_REQUEST = 'ADDITIONAL_PAYMENT_REQUEST',
  ACCIDENT_OCCURRED = 'ACCIDENT_OCCURRED',
  OTHER = 'OTHER',
}

export enum STATUS_RESERVATION {
  PENDING = '예약완료',
  RUNNING = '운행중',
  COMPLETED = '카풀완료',
  CANCEL = '예약취소',
  PENALTY = '패널티부과',
}
