import {string_terms_and_conditions} from './string-terms_and_conditions';
import {string_location_based_terms_of_use} from './string_location_based_terms_of_use';
import {string_private_policy} from './string_private_policy';

export const strings = {
  general_text: {
    please_try_again: '에러 발생했습니다. 재 시도 부탁드립니다.',
    agree: '예',
    cancel: '아니오',
    login_first: '로그인이 필요합니다.',
    are_you_sure_to_delete: '삭제 하시겠습니까?',
    you_already_like_it: '이미 좋아요를 누르셨습니다.',
    won: '원',
    address: '주소',
    phone_number: '전화번호',
    list: '목록',
    delete: '삭제',
    comment: '댓글',
    wrire_a_comment: '댓글쓰기',
    enroll: '등록',
    exit: '닫기',
    writting: '글쓰기',
    keyword_search: '키워드 검색',
    do_not_exist: '없음',
    view_more: '더 보기...',
    save: '저장하기',
    confirm: '확인',
    reply: '답장',
    increase: '증가하다',
    decrease: '감소하다',
    all: '전체',
    month: '개월',
    before: '이전',
    next: '다음',
    upload_photo: '사진첨부하기',
    revoke: '취소',
    storage: '저장',
    increase_charge: '가격 낮은순',
    decrease_charge: '가격 높은순',
  },
  month_parking_direct_list: {
    view_monthly_parking_direct_transaction: '월주차 직거래 보기',
  },
  monthly_parking_direct_details: {
    monthly_parking_direct_transaction: '월주차 직거래 보기',
    transaction_completed: '거래완료',
    transaction_trading: '거래중',
    please_input_your_comment: '댓글을 입력해 주세요.',
    parking_lot_name: '주차장명',
    amount: '금액',
    number_of_parking_spaces: '주차면수',
    view_location: '위치보기',
    operating_time: '운영시간',
    sales_day: '판매요일',
    uniqueness: '특이사항',
    representative_photo: '대표사진',
    access: '진입로',
    parking_space_1: '주차공간1',
    parking_space_2: '주차공간2',
    would_you_like_to_complete_transaction: '거래완료 하시겠습니까?',
  },
  monthly_parking_direct_registration: {
    please_inter_address: '주소를 입력해주세요.',
    please_enter_the_subject: '제목을 입력해주세요.',
    please_enter_parking_lot_name: '주차장 이름을 입력해주세요.',
    please_enter_sales_amount: '판매금액을 입력해주세요.',
    please_enter_number_of_parking_spaces: '주차면수를 입력해주세요.',
    please_enter_operating_time: '운영시간을 입력해주세요.',
    please_enter_phone_number: '핸드폰번호를 입력해주세요.',
    parking_direct_transaction_registration: '월주차 직거래 등록',
    parking_lot_address: '주차장주소',
    address_input_by_direct_input_or_button: '직접입력 또는 버튼이용하여 주소입력',
    parking_lot_name: '주차장명',
    sale_price: '판매금액',
    number_of_parking_spaces: '주차면수',
    operating_time: '운영시간',
    sales_day: '판매요일',
    parking_lot_photo: '주차장 사진등록 (최대 4장까지 등록가능)',
    choose_at_least_1_photo: '주차장 사진 최소 1장을 동록해주세요',
  },
  view_parking_location_modal: {
    view_parking_location_modal: '주차장 위치보기',
  },
  monthly_parking_direct_reply_modal: {
    write_a_comment: '댓글 쓰기',
    name: '이름',
    please_enter_your_comment: '댓글을 입력해 주세요.',
  },
  list_of_parking_lots: {
    parking_lots_total_number: '주차장 리스트 보기',
    filter_by_price: '가격순',
    filter_by_distance: '거리순',
  },
  take_photo_parking_modal: {
    enter_parking_location: '주차 위치를 입력해 주세요.',
    place_holder_text_input: '예) 지하 B31',
    confirm_submit_photo: '확인',
  },
  take_photo_parking_lot: {
    take_picture_of_parking: '주차위치 사진찍기',
  },
  parking_request_notice_board: {
    parking_request_notice: '주차문의 게시판',
    note: '글쓰기',
    permission: '작성자와 관리자만 조회할 수 있습니다',
    general_question: '자주 묻는 질문 (FAQ) 보러가기',
    modal_title: '파킹박 이벤트 혜택 알림',
    modal_content: '파킹박의 이벤트 정보 관련 PUSH 알림을 받을 수 있습니다.',
    modal_sub_content: '메인메뉴 > 환경설정 에서 변경할 수 있습니다.',
    not_confirm: '동의안함',
    confirm: '동의함',
    delete: '삭제',
    edit: '수정',
    processing: '처리 대기 중입니다.',
    contact_center_customer: '취소되었습니다. 재문의를 원하시면 고객센터에 문의해주세요.',
    waiting: '처리되셨습니다.',
    delete_confirmation: '삭제 하시겠습니까?',
  },
  add_parking_request_notice: {
    write: '글쓰기',
    please_enter_title: '제목을 입력해 주세요.',
    please_enter_info_detail: '250자 이내로 내용을 입력해 주세요.',
    please_enter_photo: '사진을 선택해주세요.',
    add_photo: '사진첨부하기',
    back_to_list: '목록',
    cancel: '취소',
    done: '저장',
  },
  parking_request_notice_question: {
    question: '자주묻는질문',
  },
  request_change_and_cancel_list: {
    title: '변경 및 취소신청',
    first_rule:
      '결제 시 입력한 입차일/시간 이후 혹은 구매하신 주차권의 이 용기간이 지난 후 입출차 여부와 상관없이 일체 취소 처리가 불가합니다.',
    second_rule: '입차일, 입차시간 변경은 입차예정일 전 1회에 한하여 변경이 가능합니다.',
    third_rule:
      '** 결제 시 입력한 입차일 / 시간 이후 혹은 구매하신 주차권의 이용기간이 지난 후 입출차 여부와 상관없이 일체 취소 처리가 불가합니다.',
    fourth_tule: '** 입차일, 입차시간 변경은 입차예정일 전 1회에 한하여 변경이 가능합니다.',
    delete_item: '삭제',
  },
  request_change_and_cancel_add: {
    write: '글쓰기',
    type_request: '요청분류',
    request_cancel: '취소',
    request_cancel_payment: '현장결제취소',
    request_change_car_number: '차량번호변경',
    request_change_time_booking: '입차시간변경',
    note: '주차문의, 긴급 출차, 기타 사항은 주차문의 게시판 혹은 고객센터 전화, 카카오톡 parkingpark 으로 연락주세요.',
    notification: '이한 내 g',
    first_notification:
      '주차문의,긴급출차, 기타사항은 주차문의 게시판 혹은 고객센터 전화, 카카오톡 파킹박으로 연락주세요.',
    second_notification:
      '취소의 경우 글의 작성 시간과 예약시간을 비교해 처리합니다. 현장결제취소의 경우 확인 후 추가적인 문자 안내가 진행됩니다.',
    third_notification: '차량번호 변경의 경우 아래에 변경된 차량번호를 입력해주시기 바라겠습니다.',
    requirement: '요구사항',
    register: '등록하기',
    text_input_placeholder:
      '요구사항을 입력해주세요. \n차량번호변경 선택 시 반드시 변경할 차량번호를 \n입력해주세요.',
    back_list: '목록',
    submit: '저장',
    cancel: '취소',
    please_select_request_type: '요청 분류를 선택해주세요.',
    please_select_request_type_again: '요청 분류를 다시 선택해주세요.',
  },
  parking_request_notice_board_detail: {
    list_question: '문의게시판',
    write_comment: '댓글쓰기',
    delete: '삭제',
    submit_comment: '전송',
    list: '목록',
  },
  coupon_box: {
    title: '쿠폰함',
    search_placeholder: '쿠폰코드를 입력해주세요.',
    coupon_registration: '쿠폰등록',
    coupon_name: '쿠폰명',
    coupon_number: '쿠폰번호',
    coupon_sub_name: '쿠폰명',
    coupon_status: '쿠폰상태',
  },
  usage_history: {
    used_history: '이용내역',
    all: '전체',
    month: '개월',
    detail: '자세히',
  },
  reservation_detail: {
    title: '예약내용',
    date_of_use: '이용일자',
    product_option: '상품옵션',
    amount_of_payment: '카드결제금액',
    reservation_for_use: '사용적립금',
    charge_for_use: '사용충전금',
    coupon_to_use: '사용쿠폰',
    receipt_application: '영수증신청',
    email_registration: '이메일등록',
    policy: '예약 취소시 환불 규정',
    back_all_money: '• 입차일자 및 입차(입력된) 시간전 : 전액환불',
    back_half_of_money: '• 월주차 등록후 또는 이용중 해지 요청시 해지수수료 2만원 부과',
    back_half_of_money2:
      '• 월주차 중간해지시 요금부과 안내\n   해지수수료 2만원 +(일최대요금 x 이용일수)',
    back_half_of_money3: '• 월주차 미등록 상태에서 시작일 전 해지시 전액 환불',
    can_not_back_money: '• 입차일자 및 입차시간 이후 : 환불 불가',
    note_first:
      '• 주차장 이용약관을 지켜주시고, 주차장 내에서 발생하는 모든 사고에 대해서는 파킹박이 책임지지않습니다.',
    note_second:
      '• 예약한 이용시간 이외에 출차할 경우에는 추가 주차요금이 과금되거나 출차가 제한될 수 있습니다.',
    info_user: '이용자정보',
    car_number: '차량번호',
    vehicle_type: '차량기종',
    vehicle_color: '차량색상',
    contact: '연락처',
    email: '이메일',
  },
  simple_reservation: {
    title: '간편예약',
    note: '내가 이용한 주차장을 클릭 한번으로 간편하게 예약할수 있어요!',
    booking: '예약',
  },
  point_management: {
    title: '적립금',
    available: '사용 가능한 적립금',
  },
  reservation: {
    text_title: '하이파킹 광화문 D타워 (월주차)',
    text_top_1: '제휴 주차면수 :',
    text_top_2: '연박불가능',
    text_top_3: '자주식',
    text_policy_1: '입차 전 결제 필수',
    text_policy_2: '(입차전 결제필수/입차 후 결제로 인한 현장결제 시 취소불가)',
    text_policy_3: '만차 혹은 현장 사정에 따라서 주차가 어려울 수 있습니다.',
    text_policy_4:
      '월 정기권 중간 해지 및 환불 희망 시,' +
      '\n' +
      '(자주묻는 게시판) FAQ를 확인해주시면 감사하겠습니다.',
    text_policy_5:
      '월주차 등록 후 이용전이라도 기본해지 수수료 2만원 부과' +
      '\n' +
      '이용중 해지 요청시 수수료2만원+(현장 일최대요금 x 이용일수)',
    description_voucher:
      '적립금은 기본 회당 1,000원까지 사용가능\n(단, 주차권요금 6,000원이상 구매시 사용가능) 월주차권 구매시에는 10만원이상 3천원,\n15만원이상 5천원까지 사용가능',
    description_voucher_1: '* 적립금 사용안내',
    description_voucher_2:
      '적립금은 기본 회당 1,000원까지 사용가능\n(단, 주차권요금 6,000원이상 구매시 사용가능)\n월주차권 구매시에는 10만원이상 3천원,\n15만원이상 5천원 까지 사용가능',
    description_charge_comment: '충전금으로 결제시 충전금 충전후 이용가능',
    content: {
      text1:
        "1.'파킹박' : \"회사\"가 컴퓨터,테블릿,스마트폰 등 정보통신기기를 이용하여 '서비스'를 제공할 수 있도록 설정한 온라인 영업장을 의 미합니다.\n",
      text2:
        "2'회원': '회원'이라 함은 회사에 개인정보를 제공하여 회원등록을 한 자로서, '파킹박'에서 제공하는 정보를 지속적으로 제공받으며, 이용할수 있는 자를 말합니다. '회사'는 서비스의 원활한 제공을 위 해 회원의 등급을 회사 내부의 규정에 따라 나눌 수 있습니다.\n",
      text3:
        "1.'파킹박' : \"회사\"가 컴퓨터,테블릿,스마트폰 등 정보통신기기를 이용하여 '서비스'를 제공할 수 있도록 설정한 온라인 영업장을 의\n",
    },
    parking_rules: {
      title: '주차장 이용규칙',
      content: '꼭 확인하세요!',
      text: '[월주차는 입차일로부터 한달 이용] 출차시 차단기가 열리지않을시차단기 옆에있는 관리자에게 파킹박앱에서 결제하신 내역(차량번호,일자)을 말씀하신 후 출차하시면 됩니다.',
    },
    parking_content: {
      text1: '선불주차권 구매 및 입차 후,',
      text2: '주차권 추가구매 사용 절대불가',
      text3: '합니다.',
      text4: '으로 부과됩니다.',
      text5: '초과사용시, 현장요금',
    },
    explore_parking: '다른 조건을 가진 주차장 둘러보기!',
    info_user: {
      title: '구매자 정보',
      content: '카드정보를 확인하세요!',
    },
    info_month_pay: {
      title: '매달 월주차권 결제가 번거로우신가요?',
      content: '자동결제 신청전 꼭 확인해 주세요!',
      c_request: '월주차권 자동결제 신청하기',
    },
    info_voucher: '할인정보',
    help: {
      title: '주차권 안내',
      content: '모든 주차권은 주차권에 안내된 시간으로만\n이용가능 합니다.',
      text1:
        '1일권 : 주차장이 정한 시간 안에서 예약일\n(당일) 사용 가능한 주차권\n(입차한 시간과는 상관없이 주차권 종료 시\n간까지 이용 가능)',
      text2: '예) 1일권(00:00-23:59) 구매 후 밤 11시\n입차해도, 입차일 23:59분까지만 이용 아가능',
      text3: '심야권 : 당일 오후 6시 이후부터 다음날(익\n일) 오전 6시까지 이용 가능한 주차권',
      text4: '연박 : 1일권 결제 후 연속으로 이어서 주차\n하는 방식(날이 바뀌면 연박)',
    },
  },
  tutorial_button: '시작하기',
  usage_history_detail: {
    header: '예약내용',
    year: '년',
    month: '월',
    day: '일',
  },
  vehicle_number: {
    title: '차량정보',
    title1: '차량번호',
    title2: '차량모델',
    title3: '차량색상',
    title4: '차량연식',
    title5: '제조사',
    title6: '차량정보 등록',
    title7: '커넥티드카 연동',
    hyundai: '현대',
    kia: '기아',
    genesis: '제네시스',
    linking: '연동중',
  },
  vehicle_number_manage: {
    title: '차량번호 관리',
  },
  valet_parking_reservation_popup: {
    cancel: '취소하기',
  },
  valet_qna_bbs_list: {
    header: '문의게시판',
    permission: '작성자와 관리자만 조회할 수 있습니다.',
  },
  valet_qna_bbs_detail: {
    empty_reply_list: '등록된 글이 없습니다.',
  },
  valet_qna_bbs_create: {
    header: '글쓰기',
    place_holder_title: '제목을 입력해 주세요.',
    place_holder_info_detail: '내용을 입력해 주세요.',
  },
  valet_payment_history_admin: {
    header: '발렛파킹 예약내역',
  },
  valet_parking_admin_reservation_1: {
    header: '1단계. 고객정보',
    parking_lot_name: '주차장명',
    car_number: '차량번호',
    car_model: '차량기종',
    car_color: '차량색상',
    contact: '연락처',
    car_together: '동행차량',
    other_request: '기타요청사항',
    main_board_image: '계기판',
    front_image: '전면',
    left_image: '측면1',
    right_image: '측면2',
    end_image: '후면',
    parking_not_not_existed:
      '운영이 중지된 주차장입니다. 실제와 정보가 다를 경우 관리자에게 문의 부탁드립니다.',
  },
  valet_parking_admin_reservation_2: {
    header: '2단계. 입/출국 정보',
    departure_information: '출국정보',
    departure_date: '출국일시',
    outbound_flight: '출국항공편',
    immigration: '입국정보',
    date_of_entry: '입국일시',
    night_departure: '야간출차',
    inbound_flight: '입국항공편',
  },
  valet_parking_admin_reservation_3: {
    header: '3단계. 발렛주차 예약',
    parking_lot_name: '주차장명',
    entry_date_and_time: '입차일시',
    departure_date_and_time: '출차일시',
    reverse: '적립금',
    coupon: '쿠폰',
    actual_payment_amount: '실 결제금액',
  },
  valet_parking_image_detail: {
    back: '나가기',
    delete: '삭 제',
  },
  consent_popup: {
    header: '파킹박 서비스 이용동의',
    term_of_use: '이용약관',
    view_content: '내용보기',
    privacy: '개인정보취급방침',
    location_information: '위치정보서비스 이용약관',
    confirm_agree_privacy: '이용약관, 개인정보취급방침, 위치정보서비스 이용 약관에 동의합니다.',
    agree: '동의합니다.',
    not_agree: '동의하지 않습니다. (앱을 종료합니다)',
    text_if_not_agree_privacy: "'파킹박'을 이용하기 위해 이용약관의 동 의가 필요합니다.",
    message_then_kill_app: "'파킹박'을 이용하기 위해 이용약관의 동의가 필요합니다.",
  },
  car_setting: {
    title: '드라이버 정보 등록',
  },
  register_car_insurance_information: {
    title: '자동차 보험정보 등록',
    car_insurance_company: '자동차보험사',
    car_insurance_company_placeholder: '선택 해주세요.',
    arr_amount_of_indemnity: ['1억', '2억', '3억', '5억', '10억'],
    subscription_status: ['가입', '미가입'],
  },
  activity_setting_license: {
    title: '운전면허 정보 등록',
  },
  setting_menu_popup: {
    reminder: '주차알람',
    message: '주차장 정보 공유',
    take_photo: '주차위치 사진찍기',
    weather: '날씨 보기',
    valet_parking: '인천공항 주차대행\n(발렛파킹) 예약',
    event: '파킹박 이벤트',
  },
  register_parking_shared: {
    title: '공유주차장 등록',
    description: '주차장 형태',
    place_holder_desc: '단독주택, 빌라 등 주차장 형태 입력',
    address: '주차장 주소',
    place_holder_address: '상세주소를 입력해주세요.',
    rate: '1일 요금 및 시간당 요금',
    place_holder_rate: '예) 1일 15,000 원 / 30분 1,000 원',
    num_of_parking: '주차면수',
    place_holder_num_parking: '주차면수를 입력해주세요.',
    sales_day: '판매요일',
    place_holder_sale_day: '예) 평일주말, 평일, 주말, 월 ~ 수, 월수금, 금 ~ 일',
    phone_number: '전화번호',
    place_holder_phone_number: '예) 01012341234',
    operating_time: '운영시간',
    place_holder_example_time: '예) 9시 ~ 18시',
    cancel_button: '취소하기',
    rule_upload_photo: '사진첨부',
    rule_upload_subtitle: '최대 4장까지 등록이 가능합니다.',
    image_1_title: '건물외관',
    image_2_title: '진입로',
    image_3_title: '주차공간1',
    image_4_title: '주차공간2',
    invalid_member_id: '회원정보가 옳바르지 않습니다.',
    invalid_address: '주차장 설명을 입력해주세요.',
    invalid_amt: '판매금액을 입력해주세요.',
    invalid_space: '운영시간을 입력해주세요.',
    invalid_sellTime: '판매요일을 입력해주세요',
    invalid_num: '핸드폰번호를 입력해주세요.',
  },
  register_parking_shared_detail: {
    header: '주차장 공유 신청현황',
    garage_name: '주차장명',
    holder_garage_name: '주차장명을 입력해주세요',
    garage_info: '주차장 설명',
    holder_garage_info: '주차장에 대한 설명을 입력해주세요',
    garage_address: '주차장주소',
    holder_garage_address: '주소를 입력해주세요',
    garage_charge: '주차비용',
    holder_garage_charge: '1일 판매금액을 입력해주세요',
    garage_num: '공유할 주차면',
    holder_garage_num: '주차면 수를 입력하세요',
    pay_day: '판매할 요일',
    holder_garage_day: '예) 월~금, 주말,평일',
    pay_time: '판매할 시간',
    holder_garage_time: '예) 9시 ~ 18시',
    shared_pnum: '핸드폰번호',
    holder_garage_pnum: '예)01034211234',
    picture_1: '사진1',
    picture_2: '사진2',
    picture_3: '사진3',
    picture_4: '사진4',
  },
  modal_weather: {
    hour: '시간',
    weather: '날씨',
    temperatures: '기온',
    probability: ' 강수확률',
    humidity: '습도',
    open_weather_text:
      '자세한 날씨정보는 "오픈웨더"를 이용해 주세요.\n(누르시면 다운로드 페이지로 이동합니다.)',
  },
  drawer: {
    usage_history: '이용내역',
    information: '개인정보관리',
    middle_charge: '충전금충전',
    charge: '충전금',
    reserves: '적립금',
    coupon_box: '쿠폰함',
    carpool: '카풀 서비스',
    airport: '공항주차',
    airport2: '공항주차2',
    monthly_direct: '월주차직거래',
    valet_parking: '발렛파킹',
    parking_share: '주차공유',
    favorite: '즐겨찾기',
    parking_alarm: '주차알람',
    take_parking_photo: '주차사진찍기',
    user_guide: '이용가이드',
    contact_us: '문의하기',
    event_banner: '제휴혜택',
    event_game: '적립금 지급혜택',
    hot_place: '핫플레이스 주차',
  },
  service_terms_and_conditions: {
    title: '약관동의',
    content: '카풀 서비스 이용을 위한 필수 약관\n및 보험 가입에 동의해주세요.',
    check1: '약관 전체동의',
    check2: '(무료)태워줘-카풀 안심보험 가입동의',
    item1: '[필수] 태워줘 서비스 이용약관',
    item2: '[필수] 개인정보 처리방침',
    item3: '[필수] 위치기반 이용약관',
    item4: '[필수] 태워줘 서비스 이용약관',

    policy: {
      title: 'KB손해보험”태워줘”카풀 안심보험 안내',
      content: [
        {title: '보험상품', content: '(무료)태워줘-카풀 안심 보험'},
        {
          title: '가입기간',
          content: '가입시~1개월(회원탈퇴시까지 1개월씩 자동연장',
        },
        {title: '참여대상', content: '“태워줘”이용고객 모두'},
        {
          title: '보장금액',
          content: '상해사장,상해 후유장애 3,000만원,폭력피해위로금 500만원',
        },
      ],
    },

    button: '확인',
  },
  terms_and_conditions: {
    title: '태워줘 서비스 이용약관',
    content: string_terms_and_conditions,
    checkbox: '위 내용에 동의합니다.',
    button: '확인',
  },
  private_policy: {
    title: '개인정보 처리방침',
    content: string_private_policy,
    checkbox: '위 내용에 동의합니다.',
    button: '확인',
  },
  location_based_terms_of_use: {
    title: '위치기반 이용약관',
    content: string_location_based_terms_of_use,
    checkbox: '위 내용에 동의합니다.',
    button: '확인',
  },
  agree_to_subscribe_to_carpool: {
    title: '태워줘-카풀 안심보험 가입동의',
    text1:
      '◆ 개인 신용정보의 제공 활용 동의\n 이 계약과 관련하여 귀사가 본인으로부터 취득한 개인신용정보를 타인에게 제공하거나 신용정보집중기관으로부터 본인의 개인신용정보를 조회하고자 하는 경우에는  "신용정보의 이용 및 보호에 관한 법률" 제32조에 따라 동의를 얻어야 합니다. 이에 피보험자 본인은 와이즈모바일(주)가 제공하는 KB손해보험㈜의 플러스사랑단체상해보험에 가입하는 것을 동의하며, 또한 "신용정보의 이용 및 보호에 관한 법률" 제32조에서 정하는 절차에 따라 개인신용정보의 제공·활용에 동의하고, 동의서에 기재하여 제공하는  신용정보의 내용에 아래의 사항이 포함됨을 확인합니다.',
    text2:
      "[개인신용정보의 제공에 관한 내용]\n- 제공대상기관: 주식회사KB손해보험\n'- 제공목적: (주)KB손해보험의 플러스사랑단체상해보험 가입\n'- 제공받는자의 정보 보유, 이용기간:  본 계약의 체결시부터 위 법 제37조에 따라 개인신용정보 제공, 이용동의를 철회한 때까지\n'- 제공할 개인신용정보의 내용\n(1) 피보험자의 성명, 연락처 등 개인식별정보\n(2) 피보험자의 \"태워줘\" 서비스 이용일/이용구간/해지일  등 보험관련 계약내용\n\n※ 무료 보험 가입에 동의합니다.",
    agree: '동의합니다.',
    text3:
      '이에 대한 내용을 설명들었으며 이를 확인하였고, 와이즈모바일(주)에서 고객님을 피보험자로 계약하는 것에 동의합니다.',
    text4:
      '상법 제731조에 의거하여 무료보험 보장내용 중 사망담보가 포함되어 있는 경우 동의를 해 주셔야만 계약이 유효하게 성립되며, 보장을 받으실 수 있습니다.\n☞ 상법제731조 (타인의 생명의 보험)\n①타인의 사망을 보험사고로 하는 보험계약에는 보험계약 체결시에 그 타인의 서면에 의한 동의를 얻어야 한다. \n②보험계약으로 인하여 생긴 권리를 피보험자가 아닌 자에게 양도하는 경우에도 제1항과같다.',
    resident_registration_number: '주민등록번호 입력 : ',
    placeholder: '000000',
    placeholderName: '홍길동',
    principle: '피보험자(본인) 성명 : ',
    name: ' 서명/인',
    button: '확인',
  },
  quick_action_memu: {
    give_me_a_drive: '카풀 서비스',
    make_commuting_more_convenient_with_carpooling: '카풀로 출퇴근을\n더욱 편리하게',
    airport_parking: '공항주차',
    parking_when_traveling_easily: '여행시 주차를\n간편하게',
    valet_parking: '발렛파킹',
    worry_about_parking_when_traveling: '여행시 주차 걱정\n그만!',
    parking_sharing: '주차공유',
    share_your_parking_lot_and_make_money: '주차장 공유하고\n수익 창출',
    monthly_parking_direct: '월주차직거래',
    parking_lot_is_also_sold_directly: '주차장도 직거래\n하자',
  },
  business_card_and_vaccine_registration: {
    title: '명함 및 백신 등록',
    cancel: '건너뛰기',
    occupation: '직종',
    placeholder_occupation: '직종을 선택해주세요.',
    detail: '상세직업',
    placeholder_detail: '상세한 직업을 입력해주세요.',
    company_name: '회사명',
    placeholder_company_name: '회사명을 입력해주세요.',
    company_address: '회사주소',
    placeholder_company_address: '회사 주소를 입력해주세요.',
    bottom_sheet: {
      title: '직종',
      contents: ['회사원', '사업가', '자영업', '전문직', '기타'],
    },
  },
  carpool_request_registration_list: {
    title: '카풀 요청 등록리스트',
    bottom_sheet_filter: {
      title: '필터링',
      route: '경로',
      viewingPeriod: '조회기간',
      wayWork: '출근길',
      wayHome: '퇴근길',
      subPeriod: '최대 2주까지 조회 가능합니다.',
      placeholderStart: '시작',
      placeholderEnd: '마지막',
      reload: '초기화',
      filter: '완료',
    },
  },
  driver_register: {
    register: '등록하기',
    quick_link: '드라이버 QUICK 등록 바로가기',
    driver_information_register: '드라이버정보등록',
    car_infor: '차량정보',
    obligate_sign_up_to_allow_pick_up:
      '카풀드라이버를 승인 받기 위해서는 차량정보 등록은 필수 입니다.',
    car_is_available_or_doesnt_allow_run: '이용 및 승인 불가 차량',
    rental_car: '렌트차량',
    shared_car: '카셰어링차량',
    car_over_10_ages: '연식10년이상 차량',
    light_car: '경차',
    car_image: '차량사진',
    quick_title: '드라이버 서류 등록이 번거로우신가요?',
    please_register_photos_of_the_front_back_sides_and_interior_of_the_car:
      '차량 앞,뒤,옆,내부 사진을 형식에 맞춰 등록해주세요!',
    quick_content:
      '친절한 파킹박 카풀 매니저가 도와드리는 드라이버 QUICK 등록 서비스를 이용해보세요!',
    vehicle_license: '운전면허',
    please_sign_up_vehicle_license: '운전 면허정보를 등록해주세요.',
    insurance_infor: '보험정보',
    please_sign_up_insurance_infor: '자동차 보험 정보를 등록해주세요.',
    choose_payment: '정산방법선택',
    please_choose_payment_when_drive_and_sign_up: '카풀정산 방식을 선택하여 등록해주세요.',
    register_vacxin_and_business_card: '백신 및 명함등록',
    please_sign_up_vacxin_certification_and_card: '백신인증 및 명함을 등록해주세요.',
    style_you_want: '원하는 스타일',
    style_register_guide:
      '- 드라이버 정보 수정을 원하시면 고객센터 문의 또는 문의하기 게시판을 통해 변경 요청내용과 증빙서류를 첨부하여 변경요청 부탁드립니다.',
    please_sign_up_style_you_want: '카풀시 원하는 스타일을 등록해주세요.',
    save: '저장하기',
    number_car: '차량번호(필수)',
    card_sample: '차량모델(필수)',
    car_year: '차량연식(필수)',
    car_color: '차량색상(선택)',
    production: '제조사(선택)',
    car_front: '차량앞면',
    car_back: '차량뒷면',
    car_side: '차량측면',
    car_inside: '차량내부',
    license_type: '면허종류',
    license_number: '면허번호',
    permanent_registration_number: '주민등록번호',
    expired_date: '갱신만료일',
    expired_license_date: '면허만료일',
    serial_number: '일렬번호',
    attach_license: '면허증 사진 첨부',
    image_background_registration: '프로필사진등록',
    expired_insurance_date: '보험종료일',
    insurance_registration: '종합보험 가입 여부',
    property_compensation_amount: '대물배상금액',
    insurance_driver_history: '운전자보험이력',
    attach_insurance_card: '보험증 사진 첨부',
    please_attach_insurance_card: '보험증 사진을 첨부해주세요.',
    business_card_and_vaccine_card: '명함 및 백신 등록',
    career: '직종',
    detail_career: '상세직업',
    name_company: '회사명',
    address_company: '회사주소',
    confirm_business_card: '명함 인증(필수)',
    optional_vaccine_certification: '코로나 백신접종 증명서(선택)',
    choose_bank: '은행선택',
    account_number: '계좌번호',
    owner_account: '예금주',
    attach_image_bank_card: '통장사진첨부',
    please_sign_up_copy_account_number: '계좌번호가 사본을 등록해주세요.',
    car_information_registration: '차량정보등록',
    sign_up_driver_license: '운전면허 정보등록',
    postCode: '지역번호',
    number: '숫자',
    area: '지역',
    choose: '선택',
    payment_registration: ['충전금입금', '계좌입금'],
    change_requirement: '변경신청',
    favorite_registration: '원하는 분위기 등록',
    gender: '성별',
    gender_data: ['성별무관', '여성만', '남성만'],
    go_plane: '좌석탑승',
    go_plane_data: ['탑승좌석 무관', '앞좌석 탑승', '뒷좌석 탑승'],
    style_into_car: '출근길 분위기',
    style_into_car_data: ['흡연무관', '음악듣기', '라디오듣기', '대화위주', '조용한'],
    routine_driver: '금액조정 요청 여부',
    routine_driver_data: ['금액조정 요청가능', '금액조정 요청불가능'],
    sign_up_payment: '계좌정보 등록',
    edit: '수정하기',
    complete_register: '등록완료',
    approved: '승인완료',
    rejected: '승인거절',
    front: '앞면',
    back: '뒷면',
    beside: '측면',
    inside: '내부',
    car_number_management: '차량번호관리',
    sign_up_your_car: '차량 등록하기',
    sign_up_new_car: '새로운 차량 등록하기',
    cancel: '취소',
    check: '확인',
    car_insurance_company: '자동차 보험사',
    sign_up_routine: '경로 등록하기',
    customer_mode: '탑승객 모드로 둘러보기',
    sign_up_communicate: '승인 재요청하기',
    status_private_insurance: '대인배상II 가입여부',
  },
  report_an_accident: {
    title: '신고하기',
    content: '‘파킹박닉네임’ 드라이버님을\n신고하는 이유를 선택해주세요.',
    question: [
      '카풀 위치에 나타나지 않았어요.',
      '카풀 차량이 등록된 차량과 달라요.',
      '불편한 대화를 해요.',
      '개인적인 거래를 요구해요.',
      '차량사고가 발생했어요.',
      '기타',
    ],
  },
  register_inquiry: {
    inquiry: ['취소', '현장결제취소', '차량번호변경', '입차시간변경', '기타'],
  },
  drive_me_home: {
    title: '반갑습니다.\n오늘도 안전 운전하세요!',
    switch_mode: '탑승객모드 전환',
  },
  driver_communication: {
    sign_up_your_way_to_work: '출근길 등록',
    tip_improve_driving_communicate: '카풀 매칭 높이는 꿀TIP',
    pass: '경유',
    go: '도착',
  },
  car_pool: {
    require_car_pool_list: '카풀 요청 등록리스트',
    require_car_pool_park_list: '제휴주차장 카풀요청 리스트',
    reply_requirements: '요청 응답하기',
    way_to_work: '출근길 등록',
  },
  choice_settlement_method: {
    title: '카풀 운행을 통해 발생한 수익금을\n지급받을 방식을 선택해주세요.',
    recharge: '충전금입금',
    account: '계좌입금',
    account_number: '계좌번호',
    account_holder: '예금주',
    requested: '정산 변경이 요청되었습니다.',
    request_message: '변경 승인 후 정산방식은\n매달 1일 변경됩니다.',
    confirm: '확인',
  },
  passenger: {
    route_list: ['전체경로', '조회기간'],
    report: '신고하기',
  },
  usage_detail: {
    driver_category_usage_detail: ['경로', '진행상태', '조회기간'],
  },
};
